global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'mindscape-api'
    static_configs:
      - targets: ['mindscape-api:8000']
    metrics_path: '/metrics'

  - job_name: 'mindscape-frontend'
    static_configs:
      - targets: ['mindscape-frontend:3000']
    metrics_path: '/metrics'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093' 